chore: simplify pre-push hook

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -1,15 +1,6 @@
 #!/bin/bash
 
-mage lint
-if [ $? -ne 0 ]; then
-    echo "Linting failed, aborting push"
-    exit 1
-fi
-
-mage test
-if [ $? -ne 0 ]; then
-    echo "Testing failed, aborting push"
-    exit 1
-fi
+mage lint || { echo "Linting failed, aborting push"; exit 1; }
+mage test || { echo "Testing failed, aborting push"; exit 1; }
 
 exit 0
