chore: add testing step to pre-push hook

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -6,4 +6,10 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
+mage test
+if [ $? -ne 0 ]; then
+    echo "Testing failed, aborting push"
+    exit 1
+fi
+
 exit 0
